extern char _binary_src_shaders_basic_vert_start;
extern char _binary_src_shaders_basic_vert_end;
extern char _binary_src_shaders_basic_vert_size;

extern char _binary_src_shaders_basic_frag_start;
extern char _binary_src_shaders_basic_frag_end;
extern char _binary_src_shaders_basic_frag_size;
